{
    "name": "Maintenance - Equipment Ownership, Stock and Assets",
    "version": "18.0.3.0.0",
    "summary": "Equipment ownership status, serial number, fixed asset, contracts "
    "and supplier bill integration (L'Art du Bâti).",
    "author": "UBI Solutions",
    "license": "LGPL-3",
    "category": "Manufacturing/Maintenance",
    "depends": [
        "maintenance",
        "stock_account",
        "purchase_stock",
        "maintenance_product",
        "maintenance_account",
        "account_asset_management",
        "contract",
        "contract_line_successor",
        "maintenance_equipment_usage",
        "stock_location_address",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/mail_activity_type.xml",
        "data/ir_cron.xml",
        "data/ir_sequence.xml",
        "wizards/ownership_correction_views.xml",
        "views/maintenance_equipment_views.xml",
        "views/stock_location_views.xml",
        "views/product_category_views.xml",
        "views/contract_line_views.xml",
        "views/account_move_views.xml",
        "views/res_config_settings_views.xml",
        "views/equipment_operation_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
